#!/usr/bin/env bash
# audit-css.sh — mechanical pass of the marble-theme skill's CSS audit (reference/css-audit.md).
#
# Runs the checks a script CAN decide for itself and emits an A–F report
# skeleton (the A–F structure is defined in the skill's SKILL.md). The
# human-judgment sections
# (which orphans are safe to drop, which bare colors map to a token) are left
# stubbed `TODO` — see the skill's SKILL.md for how to triage them.
#
# This is ADVISORY and READ-ONLY: it never edits CSS/config, and always exits 0.
# The standing build gate is `npm run lint:css`, not this script.
#
# Checks:
#   1. stylelint  — duplication / redundancy / dead CSS (via the repo .stylelintrc.json)
#   2. orphan tokens — design tokens with zero var() references anywhere
#   3. hardcoded colors — bare hex / rgb() / rgba() NOT inside a var(--x, …) fallback
#   4. duplicate box-shadow — identical literal shadow strings shared across files
#   5. default-value redundancy — `display` decls that restate the element's browser
#      default (e.g. `.z-span { display: inline }`); via check-default-display.js
#
# Usage:
#   bash audit-css.sh [options]
#     --prefix <tok>       token prefix to audit          (default: --zk-)
#     --tokens-dir <dir>   where token definitions live   (default: <web>/zul/css/tokens)
#     --css-root <dir>     root scanned for var() refs     (default: <web>)
#     --component-root <d> root scanned for hardcoded vals (default: <web>/js/zul)
#     --zk-source <dir>    ZK js/zul source (root-tag resolution for check 5)
#     --out <file>         write report here               (default: stdout)
#
# All defaults assume the standard zkThemeTemplate layout; override them when a
# new theme moves directories or changes its token prefix.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# .claude/skills/marble-theme/scripts -> project root is four levels up.
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

WEB="$PROJECT_ROOT/src/main/resources/web"
PREFIX="--zk-"
TOKENS_DIR="$WEB/zul/css/tokens"
CSS_ROOT="$WEB"
COMPONENT_ROOT="$WEB/js/zul"
ZK_SOURCE="/Users/hawk/Documents/workspace/ZK10/zk/zul/src/main/resources/web/js/zul"
OUT=""

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)         PREFIX="$2"; shift 2 ;;
        --tokens-dir)     TOKENS_DIR="$2"; shift 2 ;;
        --css-root)       CSS_ROOT="$2"; shift 2 ;;
        --component-root) COMPONENT_ROOT="$2"; shift 2 ;;
        --zk-source)      ZK_SOURCE="$2"; shift 2 ;;
        --out)            OUT="$2"; shift 2 ;;
        -h|--help)        sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done

# Use the real grep binary, not a shell shim/alias. ripgrep is intentionally NOT
# used: on some setups `rg` is only an interactive shell function with no binary,
# so it vanishes inside a script. grep is always present.
GREP="$(command -v ggrep || command -v grep)"

# Redirect all report output to --out if given.
if [ -n "$OUT" ]; then exec > "$OUT"; fi

emit() { printf '%s\n' "$*"; }

emit "# CSS Audit — mechanical pass"
emit ""
emit "> Generated by \`audit-css.sh\`. Counts are mechanical; the **TODO** sections need"
emit "> human triage per reference/css-audit.md in the marble-theme skill (see it for the worked example)."
emit ""
emit "- token prefix:    \`$PREFIX\`"
emit "- tokens dir:      \`${TOKENS_DIR#$PROJECT_ROOT/}\`"
emit "- css root:        \`${CSS_ROOT#$PROJECT_ROOT/}\`"
emit "- component root:  \`${COMPONENT_ROOT#$PROJECT_ROOT/}\`"
emit ""

# ── Check 1: stylelint (duplication / redundancy / dead CSS) ─────────────────
emit "## D. stylelint (in-file duplication / redundancy)"
emit ""
LINT_GLOB="$CSS_ROOT/**/*.css"
# Merge stderr — stylelint's JSON formatter may write to either stream depending
# on version. node then slices out the JSON array, ignoring any npm/npx noise.
LINT_RAW="$(cd "$PROJECT_ROOT" && npx --no-install stylelint "$LINT_GLOB" -f json 2>&1 || true)"
read -r ERRORS WARNINGS FILES < <(node -e '
    const raw = process.argv[1] || "";
    const s = raw.indexOf("["), e = raw.lastIndexOf("]");
    let d = [];
    if (s >= 0 && e >= s) { try { d = JSON.parse(raw.slice(s, e + 1)); } catch (_) {} }
    let er = 0, w = 0;
    for (const f of d) for (const m of (f.warnings || [])) (m.severity === "error" ? er++ : w++);
    console.log(er + " " + w + " " + d.length);
' "$LINT_RAW" 2>/dev/null || echo "? ? 0")
if [ "${FILES:-0}" -eq 0 ]; then
    emit "_stylelint produced no parseable output — is it installed? Run \`npm install\`._"
else
    emit "- **errors:** ${ERRORS}"
    emit "- **warnings:** ${WARNINGS}  _(goldenlayout's intentional split is the known-accepted warning set)_"
    emit "- files scanned: ${FILES}"
    emit ""
    emit "_Target: 0 errors. Run \`npm run lint:css\` for the full human-readable listing._"
fi
emit ""

# ── Check 2: orphan tokens (zero var() references) ───────────────────────────
emit "## A3. Orphan tokens (0 \`var()\` references)"
emit ""
emit "> ⚠️ orphan ≠ deletable. Keep complete systematic scales (typescale / motion / elevation)"
emit "> and outward-facing theme API. Only one-off aliases / unused color slots are real candidates."
emit ""
ORPHANS=0
TOKENS=()
# Token definitions look like `  --zk-foo: …;` — the name is followed by a colon.
# References (`var(--zk-foo)`) have no adjacent colon, so this matches defs only.
while IFS= read -r v; do TOKENS+=("$v"); done < <(
    "$GREP" -rhoE --include='*.css' -e "${PREFIX}[a-z0-9-]+:" "$TOKENS_DIR" 2>/dev/null \
        | sed 's/:$//' | sort -u
)
# Guard: bash 3.2 + `set -u` errors on "${empty_array[@]}", so only iterate if non-empty.
if [ "${#TOKENS[@]}" -gt 0 ]; then
    for v in "${TOKENS[@]}"; do
        refs="$("$GREP" -rohE --include='*.css' -e "var\(${v}[,)]" "$CSS_ROOT" 2>/dev/null | wc -l | tr -d ' ')"
        if [ "${refs:-0}" -eq 0 ]; then
            emit "- \`${v}\`"
            ORPHANS=$((ORPHANS + 1))
        fi
    done
fi
if [ "${#TOKENS[@]}" -eq 0 ]; then
    emit "_No tokens found under \`${TOKENS_DIR#$PROJECT_ROOT/}\` with prefix \`$PREFIX\` — check --prefix / --tokens-dir._"
fi
emit ""
emit "**${ORPHANS} orphan token(s)** out of ${#TOKENS[@]} defined. Triage each against the rule above."
emit ""

# ── Check 3: hardcoded color candidates (bare value, not a var fallback) ─────
emit "## B1. Hardcoded color candidates"
emit ""
emit "> \`var(--x, #fallback)\` is NOT a violation (defensive fallback). Only bare values below."
emit "> Map each to an equivalent token where one exists; flag the rest for a value decision."
emit ""
# Per-file: blank out /* */ comments (preserving line numbers), drop any
# var(--…) fallback group, then flag lines that still carry a *bare* color.
HARDCODED="$(
    find "$COMPONENT_ROOT" -name '*.css' -print0 \
    | xargs -0 perl -e '
        for my $file (@ARGV) {
            open my $fh, "<", $file or next;
            local $/; my $c = <$fh>; close $fh;
            $c =~ s{/\*.*?\*/}{ (my $r = $&) =~ s/[^\n]/ /g; $r }ges;  # blank comments, keep newlines
            my @lines = split /\n/, $c, -1;
            for my $i (0 .. $#lines) {
                (my $s = $lines[$i]) =~ s/var\(--[^()]*\)//g;
                print "$file:", $i + 1, ":$lines[$i]\n" if $s =~ /#[0-9a-fA-F]{3,8}\b|rgba?\(/;
            }
        }
    '
)"
if [ -n "$HARDCODED" ]; then
    HC_COUNT="$(printf '%s\n' "$HARDCODED" | wc -l | tr -d ' ')"
    emit "Found **${HC_COUNT}** candidate line(s) (paths relative to project root):"
    emit '```'
    printf '%s\n' "$HARDCODED" | sed "s#$PROJECT_ROOT/##"
    emit '```'
else
    emit "_None found._"
fi
emit ""

# ── Check 4: duplicate literal box-shadow across files ───────────────────────
emit "## B4. Duplicate literal box-shadow (DRY → shared-token candidate)"
emit ""
DUP_SHADOW="$(
    find "$COMPONENT_ROOT" -name '*.css' -print0 \
    | xargs -0 perl -e '
        my %files;
        for my $file (@ARGV) {
            open my $fh, "<", $file or next;
            local $/; my $c = <$fh>; close $fh;
            $c =~ s{/\*.*?\*/}{ }ges;                 # drop comments
            while ($c =~ /box-shadow\s*:\s*([^;]+);/gs) {
                my $val = $1;
                $val =~ s/\s+/ /g; $val =~ s/^\s+|\s+$//g;
                next if $val =~ /^var\(/;             # token reference, not a literal
                next unless $val =~ /rgba?\(|,/;      # multi-stop / color-bearing literal only
                $files{$val}{$file} = 1;
            }
        }
        for my $val (sort keys %files) {
            my @f = sort keys %{$files{$val}};
            next if @f < 2;
            print "- shared by ", scalar(@f), " files: ", join(", ", @f), "\n";
            print "  `", $val, "`\n";
        }
    ' | sed "s#$PROJECT_ROOT/##g"
)"
if [ -n "$DUP_SHADOW" ]; then
    emit "$DUP_SHADOW"
else
    emit "_No literal box-shadow string appears in 2+ files._"
fi
emit ""

# ── Check 5: default-value redundancy (display restating the element default) ─
# Delegated to a Node helper: it resolves each `.z-<name>` root tag from the ZK
# mold files and compares the declared `display` against the tag's browser default.
if command -v node >/dev/null 2>&1; then
    node "$SCRIPT_DIR/check-default-display.js" \
        --component-root "$COMPONENT_ROOT" \
        --zk-source "$ZK_SOURCE" 2>/dev/null \
    || emit "_check-default-display.js failed to run — see the skill's SKILL.md §G._"
else
    emit "## G. Default-value redundancy"
    emit ""
    emit "_node not found — skipped. Install Node to run check-default-display.js (§G)._"
fi
emit ""

# ── Human-judgment stubs ─────────────────────────────────────────────────────
emit "## Sections requiring human judgment (TODO)"
emit ""
emit "- **A1. Cross-file duplicate token definitions** — TODO: distinguish intentional responsive"
emit "  overrides (e.g. tablet layer) from real bugs."
emit "- **A4. DRY: semantic token using a literal value** — TODO."
emit "- **B2/B3. Hardcoded px / font-size** — TODO: decide whether a base token should exist."
emit "- **C. Cross-file duplicated CSS blocks** (state-layer / focus-visible) — TODO: extract vs keep."
emit "- **E. Utility-layer overlap** — TODO: confirm intentional aliases."
emit "- **F. Dead code** — TODO: needs rendered-DOM evidence; do not PurgeCSS blindly."
emit ""
emit "Write findings up using the A–F structure in reference/css-audit.md so themes stay comparable."

exit 0
